apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arcp-ingress
  namespace: arcp
spec:
  ingressClassName: nginx
  rules:
    - host: arcp.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arcp-web
                port:
                  number: 80
